### ISSUE TITLE
Quest: 'Signed in Blood' - unable to complete step 

### ISSUE THREAD

**Issue by xammy0** [OmegaPrivateServer/issues#29]
During the quest 'Signed in Blood', after retrieving the key-item "Torn-out pages" you are supposed to return to Abelard (mayor in Selbina) and speak to him to complete this step in the quest, but he doesn't respond with the correct dialogue and the quest does not advance. 

## Expected Behavior

When speaking to Abelard with the key-item "Torn-out pages", he should respond with dialogue related to the quest, and afterwards you speak with Sobane to complete the quest fully.

## Current Behavior

When speaking to Abelard while in possession of "Torn-out pages" key item, his dialogue is only related to "An Explorer's Footsteps".

I am currently on the quest "An Explorer's Footsteps" and have handed in two 'Clay Tablets' so far to Abelard. I currently have a 'Selbina Clay' in my inventory, and have tried talking to him while it was in my Mog Sack/Case/Satchel.  I couldn't find any documentation mentioning a conflict between the two quests.

After speaking with him multiple times, I decided to try to speak with Sobane to see if the step completed despite the lack of dialogue. Sobane only provides the dialogue for after the quest has been flagged, and it does not complete the quest.

## Possible Solution

I am guessing the issue is with the NPC Abelard, perhaps not recognizing the key-item in your possession

## Steps to Reproduce

1. Flag quest from Sobane by trading item "Cathedral Tapestry"
2. Have "An Explorer's Footsteps" flagged
3. Speak to Abelard - he mentions the missing pages of the diary
4. Go to Ordelle's Cave, get chest key, open chest and receive "Torn-out pages"
5. Return to Aberlard with the key item, and he does not provide the dialogue for next step in the quest.

## Detailed Description

Please determine if this is expected behavior due to quest conflict, or if he is not recognizing the key-item.

**Comment by OmegaBison** [comment]
Thanks for the detailed bug report. Well-written reports make me happy.

Abelard's scripting for this quest says:
`SIGNED IN BLOOD (will only activate if An Explorer's Footsteps is not active, or if it is completed)`

I see that your character has Explorer's Footsteps quest active.

I don't know whether this implementation is correct or not. Any feedback on whether we should update this?

**Comment by OogaBooga1316** [comment]
Mee Deggi the punisher
Domi the gallant 
And nearly every other NM in the game including 55 cap NMs

**Comment by OmegaBison** [comment]
@OogaBooga1316 Bug ticket for NMs is over this way: https://github.com/OmegaPrivateServer/issues/issues/41

**Comment by xammy0** [comment]
> 
> 
> Thanks for the detailed bug report. Well-written reports make me happy.
> 
> Abelard's scripting for this quest says:
> `SIGNED IN BLOOD (will only activate if An Explorer's Footsteps is not active, or if it is completed)`
> 
> I see that your character has Explorer's Footsteps quest active.
> 
> I don't know whether this implementation is correct or not. Any feedback on whether we should update this?

I am not certain of what is correct behavior, but the quest Explorer's Footsteps doesn't finish until you've handed in all 16 locations, and you need to be high level with multiple people to get through Eldieme Necropolis to get one of them, for example. My opinion is that you should be able to complete the quest Signed in Blood while Explorer's Footsteps is active.

**Comment by OmegaBison** [comment]
Fixed. Will go live with the next patch.

**Comment by xammy0** [comment]
Was this updated in today's patch? Notes say yes but I talked to Abelard and he still only provides dialogue for Explorer's Footsteps. I then went back to Sobane and talked to her, then back to Abelard again but issue persists.

**Comment by OmegaBison** [comment]
Confirmed fixed properly this time. Sorry about that. Changes will go live with the next patch.
